### ISSUE TITLE
template/generic instantiation of `class` from here

### ISSUE THREAD

**Issue by notchris** [jjv360/nim-classes#1]
`template/generic instantiation of `class` from here`
Unable to create a class without that error

**Comment by theAkito** [comment]
Could you post the entire code snippet of the class you are trying to create?

**Comment by jjv360** [comment]
I assume this issue is resolved, closing this for now...

**Comment by aleclarson** [comment]
I'm seeing this as well.

```
~/project/foo.nim(4, 7) template/generic instantiation of `class` from here
~/.nimble/pkgs/classes-0.2.0/classes.nim(87, 16) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
~/project/foo.nim(4, 7) template/generic instantiation of `class` from here
~/.nimble/pkgs/classes-0.2.0/classes.nim(321, 20) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
```

Here's my basic code:

``` nim
import classes

class Foo:
  var foo = true
```

### Environment
```
$ nim --version
Nim Compiler Version 1.4.8 [MacOSX: amd64]

$ nimble --version
nimble v0.13.1
```

**Comment by aleclarson** [comment]
I executed `test.nim` inside `~/.nimble/pkgs/classes-0.2.0` and got this output:

https://pastebin.com/raw/jgxEujff

**Comment by jjv360** [comment]
Hi @aleclarson - fyi this is just a warning and should not prevent the app from compiling... In the logs you posted it compiled fine and all tests were passing.

I have also pushed a new version now which should fix the warning, please try it out. I don't really understand why Nim needs methods to be explicitly marked as "base" anyway...

**Comment by aleclarson** [comment]
@jjv360 Works great, thanks!

**Comment by jjv360** [comment]
👍
