### ISSUE TITLE
Object variant support

### ISSUE THREAD

**Issue by aleclarson** [jjv360/nim-classes#2]
https://nim-lang.org/docs/tut2.html#object-oriented-programming-object-variants

My failing example:
```nim
import classes, marshal

class Foo:
  case kind: string
  of "number":
    var value: float
  of "string":
    var value: string


let foo = Foo.init(kind: "string")
foo.value = "test"

echo foo.repr
echo $$foo
```

The error:
```
~/foo.nim(5, 14) Error: invalid indentation
```

**Comment by jjv360** [comment]
This library only supports `var`, `method`, and `mixin` statements in the class body right now. I'm deliberately keeping it as simple as possible, so I don't think this syntax will work...

Besides, the docs say variants are used when "an object hierarchy is overkill", in which case you wouldn't be using a class at all anyway, I imagine...
