### ISSUE TITLE
Method overloads

### ISSUE THREAD

**Issue by aleclarson** [jjv360/nim-classes#3]
Are method overloads possible?

```nim
import classes

class Foo:
  var foo: float

  method init() =
    discard this

  method init(foo: float) =
    this.foo = foo

let foo1 = Foo(foo: 1).init()
let foo2 = Foo.init(foo: 2)

echo foo1.repr
echo foo2.repr
```

That example produces this error:
```
~/foo.nim(13, 15) Error: type expected
```

**Comment by aleclarson** [comment]
Ah crap. Excuse my noobness. The `Foo.init(foo: 2)` should be `Foo.init(2)` :)

**Comment by aleclarson** [comment]
Also, I'm curious if `discard this` is the best option there, or if there's something more concise?

I would use `method init()` without the trailing `=` if I could, but I get:
```
~/.nimble/pkgs/classes-0.2.1/classes.nim(611, 28) Error: cannot add to node kind: nnkEmpty
```

**Comment by jjv360** [comment]
👍 yeah it should work ... I think `Foo.init(foo = 2)` would work as well if you wanted to use named arguments

**Comment by jjv360** [comment]
> Also, I'm curious if `discard this` is the best option there, or if there's something more concise?
> 
> I would use `method init()` without the trailing `=` if I could, but I get:
> 
> ```
> ~/.nimble/pkgs/classes-0.2.1/classes.nim(611, 28) Error: cannot add to node kind: nnkEmpty
> ```

I think the most concise is like this:

```nim
method init() = discard
```

It would actually be possible to support blank methods without the `= discard`, but I want to leave that syntax open for implementing "abstract" classes in the future
